//pub use winit::event::VirtualKeyCode;
mod init;
pub mod shader_strings;
pub use init::*;
mod events;
pub use events::*;
mod mainloop;
use crate::hal::scaler::{default_gutter_size, ScreenScaler};
use crate::hal::ConsoleBacking;
pub use mainloop::*;
use parking_lot::Mutex;
use std::any::Any;

use serde::{Deserialize, Serialize};
#[derive(Debug, Hash, PartialEq, Eq, PartialOrd, Ord, Copy, Clone, Serialize, Deserialize)]
pub enum VirtualKeyCode {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    Return,
    Escape,
    Back,
    Tab,
    Space,
    Up,
    Down,
    Left,
    Right,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    LControl,
    RControl,
    LShift,
    RShift,
    LAlt,
    RAlt,
    Snapshot,
    Scroll,
    Pause,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    Apostrophe,
    Backslash,
    Semicolon,
    Comma,
    Convert,
    NumpadDecimal,
    NumpadDivide,
    Equals,
    Grave,
    Kana,
    LBracket,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    NumpadMultiply,
    Mute,
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RBracket,
    Slash,
    Sleep,
    Stop,
    NumpadSubtract,
    VolumeDown,
    VolumeUp,
    Wake,
    Yen,
    // 如果编译时提示还缺少某些键，按此模式继续添加
}

// 2. 实现从新版 KeyCode 到旧版 VirtualKeyCode 的映射
impl From<winit::keyboard::KeyCode> for VirtualKeyCode {
    fn from(code: winit::keyboard::KeyCode) -> Self {
        use winit::keyboard::KeyCode;
        match code {
            KeyCode::KeyA => VirtualKeyCode::A,
            KeyCode::KeyB => VirtualKeyCode::B,
            KeyCode::KeyC => VirtualKeyCode::C,
            KeyCode::KeyD => VirtualKeyCode::D,
            KeyCode::KeyE => VirtualKeyCode::E,
            KeyCode::KeyF => VirtualKeyCode::F,
            KeyCode::KeyG => VirtualKeyCode::G,
            KeyCode::KeyH => VirtualKeyCode::H,
            KeyCode::KeyI => VirtualKeyCode::I,
            KeyCode::KeyJ => VirtualKeyCode::J,
            KeyCode::KeyK => VirtualKeyCode::K,
            KeyCode::KeyL => VirtualKeyCode::L,
            KeyCode::KeyM => VirtualKeyCode::M,
            KeyCode::KeyN => VirtualKeyCode::N,
            KeyCode::KeyO => VirtualKeyCode::O,
            KeyCode::KeyP => VirtualKeyCode::P,
            KeyCode::KeyQ => VirtualKeyCode::Q,
            KeyCode::KeyR => VirtualKeyCode::R,
            KeyCode::KeyS => VirtualKeyCode::S,
            KeyCode::KeyT => VirtualKeyCode::T,
            KeyCode::KeyU => VirtualKeyCode::U,
            KeyCode::KeyV => VirtualKeyCode::V,
            KeyCode::KeyW => VirtualKeyCode::W,
            KeyCode::KeyX => VirtualKeyCode::X,
            KeyCode::KeyY => VirtualKeyCode::Y,
            KeyCode::KeyZ => VirtualKeyCode::Z,
            KeyCode::Digit1 => VirtualKeyCode::Key1,
            KeyCode::Digit2 => VirtualKeyCode::Key2,
            KeyCode::Digit3 => VirtualKeyCode::Key3,
            KeyCode::Digit4 => VirtualKeyCode::Key4,
            KeyCode::Digit5 => VirtualKeyCode::Key5,
            KeyCode::Digit6 => VirtualKeyCode::Key6,
            KeyCode::Digit7 => VirtualKeyCode::Key7,
            KeyCode::Digit8 => VirtualKeyCode::Key8,
            KeyCode::Digit9 => VirtualKeyCode::Key9,
            KeyCode::Digit0 => VirtualKeyCode::Key0,
            KeyCode::Enter => VirtualKeyCode::Return,
            KeyCode::Escape => VirtualKeyCode::Escape,
            KeyCode::Backspace => VirtualKeyCode::Back,
            KeyCode::Tab => VirtualKeyCode::Tab,
            KeyCode::Space => VirtualKeyCode::Space,
            KeyCode::ArrowUp => VirtualKeyCode::Up,
            KeyCode::ArrowDown => VirtualKeyCode::Down,
            KeyCode::ArrowLeft => VirtualKeyCode::Left,
            KeyCode::ArrowRight => VirtualKeyCode::Right,
            KeyCode::F1 => VirtualKeyCode::F1,
            KeyCode::F2 => VirtualKeyCode::F2,
            KeyCode::F3 => VirtualKeyCode::F3,
            KeyCode::F4 => VirtualKeyCode::F4,
            KeyCode::F5 => VirtualKeyCode::F5,
            KeyCode::F6 => VirtualKeyCode::F6,
            KeyCode::F7 => VirtualKeyCode::F7,
            KeyCode::F8 => VirtualKeyCode::F8,
            KeyCode::F9 => VirtualKeyCode::F9,
            KeyCode::F10 => VirtualKeyCode::F10,
            KeyCode::F11 => VirtualKeyCode::F11,
            KeyCode::F12 => VirtualKeyCode::F12,
            KeyCode::Insert => VirtualKeyCode::Insert,
            KeyCode::Home => VirtualKeyCode::Home,
            KeyCode::Delete => VirtualKeyCode::Delete,
            KeyCode::End => VirtualKeyCode::End,
            KeyCode::PageDown => VirtualKeyCode::PageDown,
            KeyCode::PageUp => VirtualKeyCode::PageUp,
            KeyCode::ControlLeft => VirtualKeyCode::LControl,
            KeyCode::ControlRight => VirtualKeyCode::RControl,
            KeyCode::ShiftLeft => VirtualKeyCode::LShift,
            KeyCode::ShiftRight => VirtualKeyCode::RShift,
            KeyCode::AltLeft => VirtualKeyCode::LAlt,
            KeyCode::AltRight => VirtualKeyCode::RAlt,
            KeyCode::PrintScreen => VirtualKeyCode::Snapshot,
            KeyCode::ScrollLock => VirtualKeyCode::Scroll,
            KeyCode::Pause => VirtualKeyCode::Pause,
            KeyCode::NumLock => VirtualKeyCode::Numlock,
            KeyCode::Numpad0 => VirtualKeyCode::Numpad0,
            KeyCode::Numpad1 => VirtualKeyCode::Numpad1,
            KeyCode::Numpad2 => VirtualKeyCode::Numpad2,
            KeyCode::Numpad3 => VirtualKeyCode::Numpad3,
            KeyCode::Numpad4 => VirtualKeyCode::Numpad4,
            KeyCode::Numpad5 => VirtualKeyCode::Numpad5,
            KeyCode::Numpad6 => VirtualKeyCode::Numpad6,
            KeyCode::Numpad7 => VirtualKeyCode::Numpad7,
            KeyCode::Numpad8 => VirtualKeyCode::Numpad8,
            KeyCode::Numpad9 => VirtualKeyCode::Numpad9,
            KeyCode::NumpadAdd => VirtualKeyCode::NumpadAdd,
            KeyCode::Quote => VirtualKeyCode::Apostrophe,
            KeyCode::Backslash => VirtualKeyCode::Backslash,
            KeyCode::Semicolon => VirtualKeyCode::Semicolon,
            KeyCode::Comma => VirtualKeyCode::Comma,
            KeyCode::Convert => VirtualKeyCode::Convert,
            KeyCode::NumpadDecimal => VirtualKeyCode::NumpadDecimal,
            KeyCode::NumpadDivide => VirtualKeyCode::NumpadDivide,
            KeyCode::Equal => VirtualKeyCode::Equals,
            KeyCode::Backquote => VirtualKeyCode::Grave,
            KeyCode::KanaMode => VirtualKeyCode::Kana,
            KeyCode::BracketLeft => VirtualKeyCode::LBracket,
            KeyCode::LaunchMail => VirtualKeyCode::Mail,
            KeyCode::MediaSelect => VirtualKeyCode::MediaSelect,
            KeyCode::MediaStop => VirtualKeyCode::MediaStop,
            KeyCode::Minus => VirtualKeyCode::Minus,
            KeyCode::NumpadMultiply => VirtualKeyCode::NumpadMultiply,
            KeyCode::AudioVolumeMute => VirtualKeyCode::Mute,
            KeyCode::MediaTrackNext => VirtualKeyCode::NextTrack,
            KeyCode::NonConvert => VirtualKeyCode::NoConvert,
            KeyCode::NumpadComma => VirtualKeyCode::NumpadComma,
            KeyCode::NumpadEnter => VirtualKeyCode::NumpadEnter,
            KeyCode::NumpadEqual => VirtualKeyCode::NumpadEquals,
            KeyCode::Period => VirtualKeyCode::Period,
            KeyCode::MediaPlayPause => VirtualKeyCode::PlayPause,
            KeyCode::Power => VirtualKeyCode::Power,
            KeyCode::MediaTrackPrevious => VirtualKeyCode::PrevTrack,
            KeyCode::BracketRight => VirtualKeyCode::RBracket,
            KeyCode::Slash => VirtualKeyCode::Slash,
            KeyCode::Sleep => VirtualKeyCode::Sleep,
            KeyCode::MediaStop => VirtualKeyCode::Stop,
            KeyCode::NumpadSubtract => VirtualKeyCode::NumpadSubtract,
            KeyCode::AudioVolumeDown => VirtualKeyCode::VolumeDown,
            KeyCode::AudioVolumeUp => VirtualKeyCode::VolumeUp,
            KeyCode::WakeUp => VirtualKeyCode::Wake,
            KeyCode::IntlYen => VirtualKeyCode::Yen,
            _ => VirtualKeyCode::Escape, // 默认兜底
        }
    }
}

pub type GlCallback = fn(&mut dyn Any, &glow::Context);

pub struct InitHints {
    pub vsync: bool,
    pub fullscreen: bool,
    pub frame_sleep_time: Option<f32>,
    pub desired_gutter: u32,
    pub fitscreen: bool,
}

impl InitHints {
    pub fn new() -> Self {
        Self {
            vsync: true,
            fullscreen: false,
            frame_sleep_time: None,
            desired_gutter: 0,
            fitscreen: false,
        }
    }
}

pub struct PlatformGL {
    pub gl: Option<glow::Context>,
    pub quad_vao: Option<glow::WebVertexArrayKey>,
    pub backing_buffer: Option<super::Framebuffer>,
    pub gl_callback: Option<GlCallback>,
    pub screen_scaler: ScreenScaler,
}

lazy_static! {
    pub static ref BACKEND: Mutex<PlatformGL> = Mutex::new(PlatformGL {
        gl: None,
        quad_vao: None,
        gl_callback: None,
        backing_buffer: None,
        screen_scaler: ScreenScaler::default(),
    });
}

unsafe impl Send for PlatformGL {}
unsafe impl Sync for PlatformGL {}

lazy_static! {
    pub(crate) static ref CONSOLE_BACKING: Mutex<Vec<ConsoleBacking>> = Mutex::new(Vec::new());
}

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    pub fn log(s: &str);
}
